[package]
name = "sp-variant"
version = "3.0.0"
edition = "2021"
authors = ["StorPool <support@storpool.com>"]
description = " Detect the Linux distribution for the StorPool build system"
readme = "README.md"
homepage = "https://github.com/storpool/sp-variant"
repository = "https://github.com/storpool/sp-variant.git"
license = "BSD-2-Clause"
categories = ["command-line-utilities", "config"]

[lib]
path = "rust/lib.rs"

[[bin]]
name = "storpool_variant"
path = "rust/bin/main.rs"

[dependencies]
anyhow = "1.0.65"
clap = { version = "4", features = ["derive"] }
nix = ">= 0.22"
once_cell = "1.15.0"
regex = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tempfile = "3"
thiserror = "1.0.36"
