[package]
name = "sp-variant"
version = "1.3.0"
edition = "2018"
authors = ["StorPool <support@storpool.com>"]
description = " Detect the Linux distribution for the StorPool build system"
readme = "README.md"
homepage = "https://github.com/storpool/sp-variant"
repository = "https://github.com/storpool/sp-variant.git"
license = "BSD-2-Clause"
categories = ["command-line-utilities", "config"]

[lib]
path = "rust/lib.rs"

[[bin]]
name = "storpool_variant"
path = "rust/bin.rs"

[dependencies]
clap = "2"
expect-exit = "0.4"
nix = "0.22"
regex = "1"
quick-error = "2"
serde = {version="1", features=["derive"]}
serde_json = "1"
tempfile = "3"
