# SPDX-FileCopyrightText: 2023  StorPool <support@storpool.com>
# SPDX-License-Identifier: BSD-2-Clause

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - toc.integrate
    - toc.follow
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
site_name: sp-variant
repo_url: https://github.com/storpool/sp-variant
repo_name: sp-variant
site_author: storpool
site_url: https://storpool.com/
site_dir: site/docs
nav:
  - 'index.md'
  - 'Changelog': 'changes.md'
  - 'API Reference': 'api.md'
markdown_extensions:
  - toc:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite:
  - pymdownx.superfences:
plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: [python]
          options:
            heading_level: 3
            show_root_heading: true
  - search
watch:
  - 'python/sp_variant'
