[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 100

[tool.pylint.messages]
disable = [
  "useless-object-inheritance",
  "super-with-arguments",
  "raise-missing-from",
  "consider-using-f-string",
]
