[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
target-version = ["py36", "py37", "py38", "py39", "py310", "py311"]
line-length = 100

[tool.mypy]
strict = true
python_version = "3.6"

[tool.pylint]
py-version = "3.6"

[tool.pylint.messages]
disable = [
]

[tool.test-stages]
stages = ["@check", "@tests"]
